import React,{useEffect,useState} from "react";
import {api} from "../services/api";
const money=v=>`₹${Number(v||0).toLocaleString("en-IN",{maximumFractionDigits:0})}`;
export default function Materials({onBack}){
 const [items,setItems]=useState([]),[orders,setOrders]=useState([]),[form,setForm]=useState({name:"",unit:"pcs",stock_qty:"",min_stock_qty:"",rate:"",supplier:""}),[error,setError]=useState("");
 async function load(){try{const [m,o]=await Promise.all([api.get("/api/v1/workshop-materials"),api.get("/api/v1/fabrication")]);setItems(m.data.items||[]);setOrders(o.data.items||[])}catch(e){setError(e.response?.data?.detail||"Materials load nahi hue.")}}
 useEffect(()=>{load()},[]);
 async function save(e){e.preventDefault();try{const {data}=await api.post("/api/v1/workshop-materials",form);setItems(v=>[...v,data]);setForm({name:"",unit:"pcs",stock_qty:"",min_stock_qty:"",rate:"",supplier:""})}catch(e){setError(e.response?.data?.detail||"Material save nahi hua.")}}
 async function txn(id,type){const q=window.prompt(type==="in"?"Kitna stock add karna hai?":"Kitna stock use hua?");if(!q)return;try{const {data}=await api.post(`/api/v1/workshop-materials/${id}/transaction`,{txn_type:type,qty:q});setItems(v=>v.map(x=>x.id===id?data:x))}catch(e){setError(e.response?.data?.detail||"Stock update nahi hua.")}}
 return <main className="page workshop-page materials-page"><div className="page-head"><div><button className="secondary" onClick={onBack}>← Dashboard</button><h1>📦 Materials</h1><p className="form-help">Stock, rate aur material usage track karein.</p></div></div>{error&&<p className="error">{error}</p>}
 <section className="panel"><h2>Add Material</h2><form className="form-grid workshop-form" onSubmit={save}><label><span>Material</span><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="MS Pipe 1x1"/></label><label><span>Unit</span><input value={form.unit} onChange={e=>setForm({...form,unit:e.target.value})}/></label><label><span>Opening Stock</span><input type="number" value={form.stock_qty} onChange={e=>setForm({...form,stock_qty:e.target.value})}/></label><label><span>Minimum Stock</span><input type="number" value={form.min_stock_qty} onChange={e=>setForm({...form,min_stock_qty:e.target.value})}/></label><label><span>Rate / Unit</span><input type="number" value={form.rate} onChange={e=>setForm({...form,rate:e.target.value})}/></label><label><span>Supplier</span><input value={form.supplier} onChange={e=>setForm({...form,supplier:e.target.value})}/></label><div className="form-actions"><button>Add Material</button></div></form></section>
 <section className="panel"><div className="toolbar"><div><h2>Material Stock</h2><span className="record-count">{items.length} items</span></div></div><div className="table-wrap"><table><thead><tr><th>Material</th><th>Stock</th><th>Rate</th><th>Stock Value</th><th>Supplier</th><th>Action</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td><strong>{x.name}</strong><br/><small>{x.unit}</small></td><td>{x.stock_qty} {x.unit}{x.stock_qty<=x.min_stock_qty&&<b className="low-stock"> Low</b>}</td><td>{money(x.rate)}</td><td>{money(x.stock_qty*x.rate)}</td><td>{x.supplier||"-"}</td><td><button className="small" onClick={()=>txn(x.id,"in")}>+ In</button> <button className="small" onClick={()=>txn(x.id,"out")}>- Use</button></td></tr>)}{!items.length&&<tr><td colSpan="6">No materials added.</td></tr>}</tbody></table></div></section>
 </main>;
}
