import React,{useEffect,useState} from "react";
import {api} from "../services/api";
const money=v=>`₹${Number(v||0).toLocaleString("en-IN",{maximumFractionDigits:0})}`;
export default function Payments({onBack}){
 const [items,setItems]=useState([]),[orders,setOrders]=useState([]),[form,setForm]=useState({work_order_id:"",amount:"",payment_method:"Cash",reference:"",date:new Date().toISOString().slice(0,10),notes:""}),[error,setError]=useState("");
 async function load(){try{const [p,o]=await Promise.all([api.get("/api/v1/workshop-payments"),api.get("/api/v1/fabrication")]);setItems(p.data.items||[]);setOrders(o.data.items||[])}catch(e){setError(e.response?.data?.detail||"Payments load nahi hue.")}}
 useEffect(()=>{load()},[]);
 async function save(e){e.preventDefault();try{const {data}=await api.post("/api/v1/workshop-payments",form);setItems(v=>[data,...v]);setForm({...form,work_order_id:"",amount:"",reference:"",notes:""})}catch(e){setError(e.response?.data?.detail||"Payment save nahi hua.")}}
 return <main className="page workshop-page payments-page"><div className="page-head"><div><button className="secondary" onClick={onBack}>← Dashboard</button><h1>💳 Payments</h1><p className="form-help">Har fabrication job ki advance aur received payment track karein.</p></div></div>{error&&<p className="error">{error}</p>}
 <section className="panel"><h2>Record Payment</h2><form className="form-grid workshop-form" onSubmit={save}><label><span>Work Order</span><select required value={form.work_order_id} onChange={e=>setForm({...form,work_order_id:e.target.value})}><option value="">Select job</option>{orders.map(o=><option key={o.id} value={o.id}>#{o.id} {o.customer} · {o.work} · {money(o.amount)}</option>)}</select></label><label><span>Amount</span><input required type="number" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label><label><span>Payment Method</span><select value={form.payment_method} onChange={e=>setForm({...form,payment_method:e.target.value})}><option>Cash</option><option>UPI</option><option>Cheque</option><option>Card</option><option>Bank Transfer</option></select></label><label><span>संदर्भ / Reference</span><input value={form.reference} onChange={e=>setForm({...form,reference:e.target.value})} placeholder="UTR / Cheque / Note"/></label><label><span>Date</span><input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label><label className="full-field"><span>Notes</span><textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><div className="form-actions"><button>Save Payment</button></div></form></section>
 <section className="panel"><div className="toolbar"><h2>Payment History</h2><span className="record-count">{items.length} entries</span></div><div className="table-wrap"><table><thead><tr><th>Date</th><th>Job</th><th>Amount</th><th>Method</th><th>Reference</th></tr></thead><tbody>{items.map(p=><tr key={p.id}><td>{p.date}</td><td>#{p.work_order_id}</td><td>{money(p.amount)}</td><td>{p.payment_method}</td><td>{p.reference||"-"}</td></tr>)}{!items.length&&<tr><td colSpan="5">No payments recorded.</td></tr>}</tbody></table></div></section>
 </main>;
}
